
services:
  # Service Postgres SQL: structured query language
  # mySQL, MSSQL, SQLite, Postgres, Oracle
  db:
    restart: always
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service Spring Boot
  springboot:
    build: .  # Dockerfile của ứng dụng Spring Boot nằm ở thư mục hiện tại
    container_name: springboot_app
    depends_on:
      - db
    ports:
      - "9090:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
